receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024

exporters:
  debug:
    verbosity: detailed
  prometheus:
    endpoint: "0.0.0.0:8889"
    namespace: "otel"
    send_timestamps: true
    metric_expiration: 180m
  zipkin:
    endpoint: "http://zipkin:9411/api/v2/spans"
    format: proto
    default_service_name: unknown-service


service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [zipkin]  # Tambahkan logging di sini
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus, debug]
